#!/usr/bin/env python3

import cmd

import dice
import dnd


class DndcmShell(cmd.Cmd):
    prompt = 'dndcm> '
    use_rawinput = True

    def do_roll(self, arg: str) -> None:
        print(dice.roll_to_str(arg))

    def do_quit(self, _: str) -> bool:
        """Exits the DnDCM"""
        return True

    def emptyline(self) -> bool:
        return False


def main():
    DndcmShell().cmdloop()


if __name__ == '__main__':
    main()

